// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iokvjcvpgasbxmyppqay.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlva3ZqY3ZwZ2FzYnhteXBwcWF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NTQxNjAsImV4cCI6MjA3NDEzMDE2MH0.nl9rkKYjasDa5QE5QBPP1m4vXebksIYYxNAF7nZF9wU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});